### ISSUE TITLE
Harriet's empty bio

### ISSUE THREAD

**Issue by harrietrs** [letsdodigital/letsdodigital.github.io#17]
Suggestion:
> Harriet is a Data Scientist with experience of applying data science techniques in both public sector and commercial settings. 
Some of her career highlights include identifying pre-cursors to frequent ambulance users for the city of Memphis, developing real-time economic indicators for the ONS, helping to establish the data science function of HM Treasury and working in the very early days of the No. 10 Downing Street data science function. She is currently leading a pilot looking at how to operationalise ethical AI development at NHS England.

**Comment by harrietrs** [comment]
@Cotswoldsmaker

**Comment by Cotswoldsmaker** [comment]
done
