### ISSUE TITLE
Module 2 Brainstorm

### ISSUE THREAD

**Issue by Cotswoldsmaker** [letsdodigital/letsdodigital.github.io#2]
https://github.com/letsdodigital/letsdodigital.github.io/blob/1b57c6d0adc0e05073a08669f65457535cc68799/learn/learn-python/module-2/topics.txt#L23

**Comment by nikdotcodes** [comment]
Some ideas from the python side

| Python Area                                                 | Difficulty |
|-------------------------------------------------------------|------------|
| Pip & Virtual Environments                                  | 1          |
| Libraries                                                   | 1          |
| Data Structures                                             | 1          |
| Object Oriented Programming                                 | 2          |
| Handling Files                                              | 1          |
| Handling Data (APIs and Databases)                          | 2          |
| Backend Python (Flask, Django)                              | 2          |
| Data Engineering (Getting data from a to   b in a nice way) | 3          |
| Data Science (AI, ML, predictive   analysis)                | 3          |
| Data Analysis (Aggregation, pretty   pictures, reporting)   | 2          |

**Comment by Cotswoldsmaker** [comment]
looks good
