### ISSUE TITLE
Add links to social media on contact page

### ISSUE THREAD

**Issue by nikdotcodes** [letsdodigital/letsdodigital.github.io#3]
As we have them, might as well flaunt them?

[twitter](https://twitter.com/letsdodigitalci)
[bluesky](https://bsky.app/profile/letsdodigital.bsky.social)
[YouTube](https://www.youtube.com/@letsdodigital9237)

**Comment by Cotswoldsmaker** [comment]
please do

**Comment by Cotswoldsmaker** [comment]
as above
